### PR TITLE
Fix text scale bug

### LINKED ISSUE #10: Auto size text does not auto-size text in the Flutter stable  v1.2.1
I was on Flutter Beta 1.0 for the longest time in one of my machines. 
Today I upgraded to Flutter Stable v1.2.1, and seems that this plugin has lost its functionality. 
Text is not being auto-sized properly, even with `maxLines` and `minFontSize` specified. 

plugin version: 1.1.1

code snippet: 
```
        Card(
          margin: EdgeInsets.only(top: 12.0),
          elevation: 4.0,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: AutoSizeText(
              "this is a very very very very very very very very very very long string",
              maxLines: 1,
              minFontSize: 2.0,
            ),
          ),
        ),
```

flutter doctor output: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648],
    locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected device (1 available)
```

### PR DESCRIPTION
**Pull request by siqwin**
Fix #10

### CODE REVIEW

**Comment by leisim** [comment]
Thanks for the pull request but I found a fix which still allowes custom scale.

**Comment by siqwin** [comment]
I tried your last version and it not working for me: if custom scale is set (big size), and there is not enough space for text, then it simply does not fit (clip). Please check it. By the way, I did not remove the custom scaling option in the pull request.

**Comment by leisim** [comment]
Could you please provide a small sample which shows the issue?

**Comment by siqwin** [comment]
Sorry, I tried it on an empty project and the latest version works fine. Thank you!

**Comment by leisim** [comment]
Perfect :)

**Pull request closed without merging**
