### PR TITLE
Add textBuilder param 

### PR DESCRIPTION
**Pull request by esDotDev**
Adds ability to supply our own TextWidget.

Addresses: https://github.com/leisim/auto_size_text/issues/84

### CODE REVIEW

**Comment by esDotDev** [comment]
Would you be able to land this?? It's extremely non-invasive and a nice add.

**Comment by leisim** [comment]
Yes looks good. Would you mind adding a small section to the readme? And maybe document the new property. Thanks :)

**Comment by esDotDev** [comment]
Should be good to go

**Comment by esDotDev** [comment]
I tweaked it a bit to include the size in the Style, and add the Data param for more flexible usage.

**Comment by esDotDev** [comment]
> Yes looks good. Would you mind adding a small section to the readme? And maybe document the new property. Thanks :)

Hi can we land this pretty-please!? Would love to remove this fork dep from my yaml file

**Comment by leisim** [comment]
It's probably a better idea to create a dedicated widget for this purpose. TextFields have margin and padding that would result in incorrect font sizes.

**Comment by esDotDev** [comment]
Not if you zero them out... which you would likely do in this use case.

**Comment by esDotDev** [comment]
Also this is just one example use case, basically in any use case where we want to lean on your widget to calculate the target fontSize, but then do "whatever else" after that point, this would enable that.

**Comment by esDotDev** [comment]
Here you can see we used it to do some quite advanced logic, it worked awesome. We switch between a regular Text and a TextField when the thing is tapped, and have styled the TextField to exactly match the padding you get with Text:

https://github.com/gskinnerTeam/flutter-folio/blob/f1a42df97609e0b28b03422a02b5b7a4cb04745b/lib/views/editor_page/placed_scrap_renderer.dart#L132

**Comment by leisim** [comment]
@esDotDev That's really cool thanks for sharing. I started working on a `AutoSizeBuilder` widget that can be used for anything and also `AutoSizeTextField` and `AutoSizeSelectableText`. What do you think about that?

**Comment by esDotDev** [comment]
Sounds cool! So that would really just focus on producing `double size` value, and then we can do anything we need with it?

**Comment by leisim** [comment]
Yes exactly. It's mostly used as a common builder for all the other AutoSize widgets and it should communicate with the `AutoSizeGroup`

**Pull request closed without merging**
